//! Desktop device identity.
//!
//! Migration `20260915160000` contract (ADR-013): `device_public_id` is an
//! opaque, cryptographically random PUBLIC identifier generated by the
//! client — never a hardware identifier, never a hash of a secret. It
//! identifies the row for UI/API operations; it is not an authentication
//! secret and possession proves nothing.

use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
use rand::RngCore;
use serde::{Deserialize, Serialize};

/// Generate a fresh opaque device id (`dev_` + 128 random bits, base64url).
pub fn new_device_public_id() -> String {
    let mut bytes = [0u8; 16];
    rand::thread_rng().fill_bytes(&mut bytes);
    format!("dev_{}", URL_SAFE_NO_PAD.encode(bytes))
}

/// Device registration payload (mirrors the `devices` table client columns).
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct DeviceRecord {
    pub device_public_id: String,
    /// `macos` | `windows` | `linux` (server CHECK constraint).
    pub platform: String,
    pub app_version: String,
}

impl DeviceRecord {
    pub fn new(device_public_id: String, platform: &str, app_version: &str) -> Self {
        Self {
            device_public_id,
            platform: platform.to_string(),
            app_version: app_version.to_string(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn device_ids_are_opaque_and_unique() {
        let a = new_device_public_id();
        let b = new_device_public_id();
        assert!(a.starts_with("dev_"));
        assert_ne!(a, b);
        // 16 bytes base64url -> 22 chars + 4 prefix.
        assert_eq!(a.len(), 4 + 22);
    }

    #[test]
    fn record_serializes_client_columns_only() {
        let record = DeviceRecord::new("dev_x".to_string(), "macos", "0.1.0");
        let json = serde_json::to_value(&record).unwrap();
        assert_eq!(json["device_public_id"], "dev_x");
        assert_eq!(json["platform"], "macos");
        assert_eq!(json["app_version"], "0.1.0");
        // No secret, no hardware identifier, no token material.
        assert!(json.get("id").is_none());
        assert!(json.get("token").is_none());
    }
}
