[package]
name = "soravo-audio"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
anyhow = "1.0"

cpal = "0.18"
rtrb = "0.4"
rubato = "0.16"
earshot = "1.2"
vad-rs = { git = "https://github.com/cjpais/vad-rs", default-features = false }

[lints]
