-- CLOUD-005: Devices / sessions foundation.
--
-- Introduces the application `devices` and `sessions` tables — the
-- device-registration and session-registry metadata for Soravo (02_TDD.md
-- §12–13; ADR-013). The customer dashboard (WEB-008) derives its device list,
-- active-session list, and "logout this session / logout other sessions"
-- actions from these tables; device/entitlement licensing (CLOUD-012) derives
-- device access from `devices.revoked_at`.
--
-- Security model (ADR-013):
--   * Device IDs are NOT authentication secrets (09_SECURITY_BASELINE.md §14).
--     `device_public_id` / `session_public_id` are opaque, cryptographically
--     random PUBLIC identifiers generated by the client — never hardware
--     identifiers, never hashes of a secret, never raw tokens. They identify a
--     row for UI/API operations; proof of possession is NOT an authorization
--     mechanism.
--   * `public.sessions` is a SESSION-REGISTRY METADATA row, not a credential.
--     The authoritative authentication session is owned by Supabase Auth
--     (`auth.sessions`); no access tokens, refresh tokens, session hashes, or
--     passwords are ever stored here. Actual credential revocation (kill an
--     Supabase session server-side) belongs to CLOUD-008; this table records
--     the same lifecycle at the application layer so the dashboard can list
--     and revoke sessions.
--   * Client self-service registration is REQUIRED by the architecture (the
--     desktop app and website act as authenticated Supabase clients; there is
--     no application server before CLOUD-009). Every client write is
--     self-scoped: policies authorize only rows owned by auth.uid(), and the
--     timestamps/identity/revocation triggers make server-owned state
--     unfakeable (SECURITY INVOKER, search_path pinned).
--   * sessions INSERT/UPDATE additionally verify that the referenced device
--     is the CALLER'S OWN device (RLS EXISTS subquery over devices) — a user
--     can never attach a session to another user's device.
--   * Revocation is one-way and terminal: once `revoked_at` is set it cannot
--     be cleared, and a revoked device/session can no longer mutate ANY of its
--     rows or (for devices) register new sessions (RLS USING
--     `revoked_at is null` + the session device-ownership subquery also
--     requiring a non-revoked device). Revocation is a user-initiated security
--     state ("remove this device" / "logout this session"); admin revocation is
--     CLOUD-006 and is not built here.
--   * No DELETE grant/policy: rows are retained for audit/metrics; user
--     deletion cascades through auth.users (FK ON DELETE CASCADE).
--
-- Privacy (01_PRD.md §10): only device/session metadata above. No audio,
-- transcripts, keystrokes, clipboard contents, or history; no hardware serial
-- numbers or MAC addresses.

begin;

-- ------------------------------------------------------------------ --
-- devices                                                            --
-- ------------------------------------------------------------------ --
create table public.devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  device_public_id text not null,
  platform text not null,
  app_version text not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  constraint devices_public_id_length check (char_length(device_public_id) between 8 and 200),
  constraint devices_platform_check check (platform in ('macos', 'windows', 'linux')),
  constraint devices_app_version_length check (char_length(app_version) between 1 and 32),
  constraint devices_revoked_at_not_before_first_seen check (
    revoked_at is null or revoked_at >= first_seen_at
  ),
  constraint devices_public_id_unique unique (device_public_id)
);

comment on table public.devices is
  'Registered Soravo devices owned by users. device_public_id is a PUBLIC opaque '
  'identifier, never an authentication secret; no hardware identifiers are stored. '
  'Stores no audio, transcripts, keystrokes, clipboard contents, or history.';

alter table public.devices enable row level security;

-- Server-owned first_seen/last_seen. first_seen_at is set only on INSERT and
-- is immutable thereafter (see identity guard); last_seen_at refreshes on every
-- write. A client cannot forge or backdate either value.
create or replace function public.devices_set_timestamps()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  if tg_op = 'INSERT' then
    new.first_seen_at := now();
  end if;
  new.last_seen_at := now();
  return new;
end;
$$;

-- Identity columns (id, user_id, device_public_id, first_seen_at) are
-- immutable for every writer, including the future licensing server: a device
-- registration can never be retargeted or re-keyed in place.
create or replace function public.devices_guard_identity()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  if new.id is distinct from old.id
     or new.user_id is distinct from old.user_id
     or new.device_public_id is distinct from old.device_public_id
     or new.first_seen_at is distinct from old.first_seen_at then
    raise exception 'devices: identity columns are immutable';
  end if;
  return new;
end;
$$;

-- Revocation is irreversible. A revoked row is a security state; clearing it
-- would let a revoked device silently regain access.
create or replace function public.devices_guard_revocation()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  if old.revoked_at is not null and new.revoked_at is null then
    raise exception 'devices: revocation is irreversible';
  end if;
  return new;
end;
$$;

revoke all on function public.devices_set_timestamps() from public, anon, authenticated, service_role;
revoke all on function public.devices_guard_identity() from public, anon, authenticated, service_role;
revoke all on function public.devices_guard_revocation() from public, anon, authenticated, service_role;

create trigger devices_set_timestamps
  before insert or update on public.devices
  for each row
  execute function public.devices_set_timestamps();

create trigger devices_guard_identity
  before update on public.devices
  for each row
  execute function public.devices_guard_identity();

create trigger devices_guard_revocation
  before update on public.devices
  for each row
  execute function public.devices_guard_revocation();

-- Self-owned access only: a user reads, registers, and maintains their OWN
-- devices. WITH CHECK prevents claiming another user's device row.
create policy "devices_select_own" on public.devices
  for select to authenticated
  using (user_id = (select auth.uid()));

create policy "devices_insert_own" on public.devices
  for insert to authenticated
  with check (user_id = (select auth.uid()));

create policy "devices_update_own" on public.devices
  for update to authenticated
  using (user_id = (select auth.uid()) and revoked_at is null)
  with check (user_id = (select auth.uid()));

-- A revoked device can no longer mutate its row: USING `revoked_at is null`
-- reads the CURRENT (pre-update) row, so the one-time revocation UPDATE still
-- passes (old revoked_at is null) while every later UPDATE is denied. Clearing
-- revoked_at is additionally rejected by the revocation trigger.

-- Deliberately no DELETE policy:
-- device rows are retained; account deletion cascades from auth.users.

grant select, insert, update on table public.devices to authenticated;

-- User→device lookups (dashboard device list, licensing reads).
create index devices_user_id_idx on public.devices (user_id);

-- ------------------------------------------------------------------ --
-- sessions                                                           --
-- ------------------------------------------------------------------ --
create table public.sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  device_id uuid not null references public.devices (id) on delete cascade,
  session_public_id text not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  constraint sessions_public_id_length check (char_length(session_public_id) between 8 and 200),
  constraint sessions_revoked_at_not_before_created check (
    revoked_at is null or revoked_at >= created_at
  ),
  constraint sessions_public_id_unique unique (session_public_id)
);

comment on table public.sessions is
  'Application session-registry metadata for Soravo devices. session_public_id '
  'is a PUBLIC opaque identifier, never an authentication secret; no access/refresh '
  'tokens or passwords are stored. Authoritative credential sessions live in '
  'Supabase Auth (auth.sessions); this table mirrors lifecycle state for the '
  'dashboard. Stores no audio, transcripts, keystrokes, clipboard contents, or history.';

alter table public.sessions enable row level security;

-- Server-owned created/last_seen. created_at is set only on INSERT and is
-- immutable thereafter; last_seen_at refreshes on every write.
create or replace function public.sessions_set_timestamps()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  if tg_op = 'INSERT' then
    new.created_at := now();
  end if;
  new.last_seen_at := now();
  return new;
end;
$$;

-- Identity columns (id, user_id, device_id, session_public_id, created_at) are
-- immutable: a session can never be retargeted to another user or device.
create or replace function public.sessions_guard_identity()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  if new.id is distinct from old.id
     or new.user_id is distinct from old.user_id
     or new.device_id is distinct from old.device_id
     or new.session_public_id is distinct from old.session_public_id
     or new.created_at is distinct from old.created_at then
    raise exception 'sessions: identity columns are immutable';
  end if;
  return new;
end;
$$;

-- Revocation is irreversible (session termination is one-way; a new sign-in
-- creates a new row).
create or replace function public.sessions_guard_revocation()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  if old.revoked_at is not null and new.revoked_at is null then
    raise exception 'sessions: revocation is irreversible';
  end if;
  return new;
end;
$$;

revoke all on function public.sessions_set_timestamps() from public, anon, authenticated, service_role;
revoke all on function public.sessions_guard_identity() from public, anon, authenticated, service_role;
revoke all on function public.sessions_guard_revocation() from public, anon, authenticated, service_role;

create trigger sessions_set_timestamps
  before insert or update on public.sessions
  for each row
  execute function public.sessions_set_timestamps();

create trigger sessions_guard_identity
  before update on public.sessions
  for each row
  execute function public.sessions_guard_identity();

create trigger sessions_guard_revocation
  before update on public.sessions
  for each row
  execute function public.sessions_guard_revocation();

-- Self-owned access only. INSERT and UPDATE additionally require that the
-- referenced device belongs to the caller AND is not revoked: the EXISTS
-- subquery resolves through devices RLS (only the caller's own device rows are
-- visible), so a session can never be bound to another user's device and a
-- revoked device can never spawn new sessions.
create policy "sessions_select_own" on public.sessions
  for select to authenticated
  using (user_id = (select auth.uid()));

create policy "sessions_insert_own" on public.sessions
  for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and exists (
      select 1 from public.devices d
      where d.id = device_id
        and d.user_id = (select auth.uid())
        and d.revoked_at is null
    )
  );

create policy "sessions_update_own" on public.sessions
  for update to authenticated
  using (user_id = (select auth.uid()) and revoked_at is null)
  with check (
    user_id = (select auth.uid())
    and exists (
      select 1 from public.devices d
      where d.id = device_id
        and d.user_id = (select auth.uid())
        and d.revoked_at is null
    )
  );

-- A revoked session can no longer mutate its row (USING `revoked_at is null`
-- reads the pre-update row, so the one-time revocation UPDATE still passes).
-- Clearing revoked_at is additionally rejected by the revocation trigger.

-- Deliberately no DELETE policy.

grant select, insert, update on table public.sessions to authenticated;

-- User→sessions and device→sessions lookups (dashboard session list, "logout
-- other sessions", device lifecycle queries).
create index sessions_user_id_idx on public.sessions (user_id);
create index sessions_device_id_idx on public.sessions (device_id);

commit;